# Generated by Django 6.0.1 on 2026-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AddField(
            model_name='program',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers (e.g., 1) appear first'),
        ),
    ]
