# Generated by Django 6.0.1 on 2026-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_options_program_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('program_name', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brochure Submission',
                'verbose_name_plural': 'Brochure Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
