# Generated by Django 6.0.3 on 2026-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_brochuresubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochuresubmission',
            name='program_name',
            field=models.CharField(max_length=500),
        ),
    ]
